### ISSUE TITLE
[Bug]: An error that I can't solve

### ISSUE THREAD

**Issue by Kakao-Team** [Simnico99/MicaWPF#104]
### Describe the bug

I installed everything as it should be, but the project throws up a lot of errors and the style doesn't work.

### Steps to reproduce the bug

none

### Expected behavior

none

### Screenshots

![Sleekshot 2024-08-02 13-13-59](https://github.com/user-attachments/assets/8465c712-a516-41d0-9f24-dcf7bd6b1e6a)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### .Net Version

.Net Framework 4.8.x

### .MicaWPF Version

MicaWPF

### Additional context

none

**Comment by Kakao-Team** [comment]
I installed the settings of the Nuget package reference and reinstalled the package but nothing changed

**Comment by Simnico99** [comment]
Its caused by your Visual studio its because the .Net Framework use Packages.config by default you need to upgrade to package references instead.

See how to migrate here:
https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
