### ISSUE TITLE
Title Foreground Doesn't Change When Window Deactivated

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#12]
When a `Window` is deactivated you can see that the window caption buttons change to a light gray color, however, the title does not.
![image](https://user-images.githubusercontent.com/17648453/166689597-41c49c99-c05b-4eb8-9251-e4914b541c58.png)
Could we see the Title change to a light gray color when the window is deactivated as well, since this is common behavior in windows:
![image](https://user-images.githubusercontent.com/17648453/166689728-a570cc77-2164-4dc9-992e-1f02d09d50d4.png)
Expected light mode behavior as well:
![image](https://user-images.githubusercontent.com/17648453/166689899-7eb14145-46ee-4405-8657-5d534596d765.png)

**Comment by Simnico99** [comment]
Windows only does it for Win32 applications I could add it as optional
![image](https://user-images.githubusercontent.com/80013536/166690382-eb9a23c9-8f1d-4c3f-98ed-709b7d364680.png)

**Comment by nlogozzo** [comment]
Oh, I didn't know it was only for Win32. That's funny since [WinUI Custom TitleBar Docs](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk) mention this: 
![image](https://user-images.githubusercontent.com/17648453/166691088-8e3f1f1e-8004-4225-80c1-4227398969e2.png)
I would add it as an optional property please :)

**Comment by Simnico99** [comment]
> Oh, I didn't know it was only for Win32. That's funny since [WinUI Custom TitleBar Docs](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk) mention this: ![image](https://user-images.githubusercontent.com/17648453/166691088-8e3f1f1e-8004-4225-80c1-4227398969e2.png) I would add it as an optional property please :)

Wow microsoft not following their own Guidelines again *Facepalm*

**Comment by Simnico99** [comment]
Will push in next update:
![image](https://user-images.githubusercontent.com/80013536/166692874-d899d92c-e8ec-403d-8e69-629071fb6ae8.png)

**Comment by nlogozzo** [comment]
Love it :) Thanks

**Comment by nlogozzo** [comment]
Lmk once you upload the new version I'll test it and let you know how it looks

**Comment by Simnico99** [comment]
Published Release its going through the Pipeline and should be available soon I had to change alot of things in the Wiki Since the logic for Accent and Theme changed.

https://github.com/Simnico99/MicaWPF/releases/tag/3.1.0

**Comment by nlogozzo** [comment]
Works beautifully! Thanks for the update :)
