### ISSUE TITLE
[Feature Request] Content in TitleBar

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#13]
Many modern windows applications support adding content inside of the open space in  the TitleBar:
![image](https://user-images.githubusercontent.com/17648453/167698884-6d90cc12-d2d9-4015-b5e2-4bd384e02b62.png)

Example:
![image](https://user-images.githubusercontent.com/17648453/167699003-5dffb3aa-4f17-4acf-b15a-9374efddb317.png)

Could we see a property of `MicaWindow` to add content inside this open space? Maybe something like:
```xml
<MicaWindow.TitleBarContent>
    <DockPanel>
        ...
    </DockPanel>
</MicaWindow.TitleBarContent>
```

**Comment by Simnico99** [comment]
Added it will push in the new version

```Xaml
    <mica:MicaWindow.TitleBarContent>
        <StackPanel Orientation="Horizontal">
            <TextBlock VerticalAlignment="Center">Hello From the TitleBar!</TextBlock>
            <controls:MicaButton Margin="5,0,0,0" Content="TitleBar Button!" />
        </StackPanel>
    </mica:MicaWindow.TitleBarContent>
```

![image](https://user-images.githubusercontent.com/80013536/168126421-01f231c9-75cc-417b-aa60-d6ea273989e4.png)

**Comment by Simnico99** [comment]
Pushed Version 3.1.3 Should be live in a couple of minutes.

**Comment by Simnico99** [comment]
Sorry for the slow update in the later days I had to go to the hospital since I've hurt my head at work.

**Comment by Simnico99** [comment]
Added the property to the wiki too

**Comment by nlogozzo** [comment]
> Added it will push in the new version
> 
> ```
>     <mica:MicaWindow.TitleBarContent>
>         <StackPanel Orientation="Horizontal">
>             <TextBlock VerticalAlignment="Center">Hello From the TitleBar!</TextBlock>
>             <controls:MicaButton Margin="5,0,0,0" Content="TitleBar Button!" />
>         </StackPanel>
>     </mica:MicaWindow.TitleBarContent>
> ```
> 
> ![image](https://user-images.githubusercontent.com/80013536/168126421-01f231c9-75cc-417b-aa60-d6ea273989e4.png)

Oh beautiful! Looks amazing!


> Sorry for the slow update in the later days I had to go to the hospital since I've hurt my head at work.

And no worries! Hope everything is ok :) . Will test in my app now...

**Comment by nlogozzo** [comment]
One little thing. I have content defined as:
```xml
    <mica:MicaWindow.TitleBarContent>
        <DockPanel LastChildFill="False">
            <TextBlock DockPanel.Dock="Right" Text="UserAccountName"/>
        </DockPanel>
    </mica:MicaWindow.TitleBarContent>
```
And this is the result:
![image](https://user-images.githubusercontent.com/17648453/168144320-cd57ae94-a11e-40b5-9b88-04982bb73ccf.png)

I expect the UserAccountName to be on the right side of the window right before the window caption buttons.
Could you have the ContentControl that hosts the TitleBarContent stretch horizontally?

**Comment by Simnico99** [comment]
Modified it to use a Docking panel instead of the StackPanel it was using to allow me to put things right and left of it
Now it does this
![image](https://user-images.githubusercontent.com/80013536/168180074-b7058701-408f-41c7-bbf1-e40eea2c7b5d.png)

**Comment by Simnico99** [comment]
Pushing 3.1.7 should be up soon™

**Comment by Simnico99** [comment]
Correction 3.1.14

**Comment by nlogozzo** [comment]
Beautiful. Downloading the update now to test...

**Comment by nlogozzo** [comment]
Works great! Thanks for the update!!
