### ISSUE TITLE
[Bug] Setting NoResize on Window removes rounded corners

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#16]
I have a splash screen window with `ResizeMode="NoResize"` set on the `MicaWindow`. 

Staring with version 3.1.16, the window is no longer rounded when NoResize is set:
![image](https://user-images.githubusercontent.com/17648453/168408288-962f379b-1f2e-4222-a38f-4aa28df88641.png)

Edit: The red dot is from Snipping Tool, not the application.

**Comment by nlogozzo** [comment]
Also, a separate issue, but with the same splash screen window, just upgrading to version 3.1.16 adds this big space in the title bar.

Below is the 3.1.15 version:
![image](https://user-images.githubusercontent.com/17648453/168408392-dd27b9ed-d569-4898-b173-9af35e38b812.png)

Just upgrading to 3.1.16, results in the image in the original post above.

**Comment by Simnico99** [comment]
Fascinating wasn't expecting that I will try that out and see how I will fix it.

**Comment by Simnico99** [comment]
The only fix I found is if CanResize is not CanResize then use Win32 Behaviors and it works:
![image](https://user-images.githubusercontent.com/80013536/168491530-b78d1238-cd05-4312-8750-783e2c02b412.png)

**Comment by Simnico99** [comment]
Pushed version 3..1.17

**Comment by nlogozzo** [comment]
Fixed with 3.1.20
