### ISSUE TITLE
[Bug] ChangeTitleColorWhenInactive doesn't change WinUI Caption Buttons

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#17]
When setting `ChangeTitleColorWhenInactive="True"` the caption buttons of the WinUI type TitleBar do not change when the Window is inactive, whereas with Win32 it does.

Win32 Inactive:
![image](https://user-images.githubusercontent.com/17648453/168498950-59dd1daf-792c-419c-a638-dd32eb98e7dd.png)

WinUI Inactive:
![image](https://user-images.githubusercontent.com/17648453/168498969-ad6d0918-8322-497f-9e6c-4273b2d2dddb.png)

**Comment by Simnico99** [comment]
I've attached the Foreground color to the one of the TextBlock now it behaves properly
![image](https://user-images.githubusercontent.com/80013536/168499337-18a92f15-a308-47ea-a651-78dadf73ff11.png)

**Comment by Simnico99** [comment]
Pushing version 3.1.22

**Comment by nlogozzo** [comment]
Fixed with V3.1.22
