### ISSUE TITLE
[Bug] Button in TitleBarContent not clickable

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#18]
I have TitleBarContent defined as:
```xml
    <mica:MicaWindow.TitleBarContent>
        <DockPanel LastChildFill="False">
            <Button DockPanel.Dock="Right">
                <Button.Content>
                    <StackPanel Orientation="Horizontal">
                        <TextBlock VerticalAlignment="Center" FontFamily="Segoe Fluent Icons" Text="&#xea8f;"/>

                        <TextBlock Margin="8,0,0,0" Text="Notifications"/>
                    </StackPanel>
                </Button.Content>
            </Button>
        </DockPanel>
    </mica:MicaWindow.TitleBarContent>
```

Whether TitleBarType is Win32 or WinUI, the button in the TitleBarContent is not clickable.

(Note: I feel like this worked before the Win32/WinUI TitleBar separation, but I'm not too sure)

**Comment by Simnico99** [comment]
Ah ```WindowChrome.IsHitTestVisibleInChrome="True"``` disapeared after a merge request I will re-add it.

**Comment by Simnico99** [comment]
Pushing 3.1.26
![cd58196cdbc43367f12edb7843edaccb](https://user-images.githubusercontent.com/80013536/168510986-920382c5-cf21-46ed-9ae1-211b8801cd71.gif)

**Comment by nlogozzo** [comment]
Waiting for Nuget...quick question, what software do you use to capture quick screen recordings like that?

**Comment by Simnico99** [comment]
Gyazo GIF

**Comment by nlogozzo** [comment]
Fixed :)
![capture](https://gyazo.com/2a8b60eaab70505ad9c9af784bcda021)
