### ISSUE TITLE
Doesn't work with XAML Islands

### ISSUE THREAD

**Issue by Pietro228** [Simnico99/MicaWPF#19]
**Describe the bug**
I got an error when using MicaWPF with XAML Islands on .NET Core 3.1

**To Reproduce**
1. Create XAML Islands for .NET Core 3.1
2. Install MicaWPF
3. Use MicaWindow
4. You'll get an error 

**Expected behavior**
My window should have mica effect.

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/53868994/170889033-f8d6843c-6fc5-4265-89e9-85bcbea5e0f0.png)

**Desktop (please complete the following information):**
 - OS Version:  Win 11 22621.1
 - .Net Version: Net Core 3.1

**Comment by Pietro228** [comment]
Only works with version 2.0, newer versions throw that error

**Comment by Simnico99** [comment]
Might be caused by the fact that 3.0.0 and over uses an extra dll to speak to uwp to get the current windows accurately. I will investigate further.

**Comment by Simnico99** [comment]
Do you have a sample project I could use to try it out it would help me alot?

Thank you!

**Comment by Simnico99** [comment]
Version 4.2.0 should have fixed it can you confirm?

**Comment by Simnico99** [comment]
I've tried it out and it seems to work fine now on netcore3.1 this issue is considered fixed if you try and still have the issue don't hesitate to reopen it.
