### ISSUE TITLE
EnableMica function doesn't work

### ISSUE THREAD

**Issue by Pietro228** [Simnico99/MicaWPF#2]
Hi,

I've done everything like in your "Usage" to enable Mica effect but it can't find the class.

![obrazek](https://user-images.githubusercontent.com/53868994/143884719-9ca112ee-c5f0-49e0-9d42-7bd5b1c4d10a.png)

**Comment by Pietro228** [comment]
I've fixed it by myself by looking into source code. I needed to use MicaHelper class. **Please update your README.md**

**Comment by Simnico99** [comment]
Will do on e at my computer
