### ISSUE TITLE
Change SystemBackdropType but the effect does not change

### ISSUE THREAD

**Issue by CodingOctocat** [Simnico99/MicaWPF#21]
**Describe the bug**
In the [MicaWindow--Properties](https://github.com/Simnico99/MicaWPF/wiki/MicaWindow--Properties), we can see that the effect of different `SystemBackdropType` varies greatly, but I tried it and found that `Tabbed`, `Acrylic`, and `None` all have the same effect as `Mica`.

**To Reproduce**
1. Just create a Blank WPF project like document.

```XAML
<mica:MicaWindow x:Class="WpfApp1.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF"
                 Title="MainWindow"
                 Width="800"
                 Height="450"
                 SystemBackdropType="None"
                 mc:Ignorable="d">
    <Grid />
</mica:MicaWindow>
```

**Screenshots**
This is the effect when `SystemBackdropType=None`, which is the same as the `Mica` effect. the same is true for `Tabbed` and `Acrylic`.
![Snipaste_2022-06-28_12-29-18](https://user-images.githubusercontent.com/7220248/176092697-4f1440be-4fbc-4573-b85f-b01357667571.png)

**Desktop (please complete the following information):**
 - OS Version
   > 版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎11/‎7 ‎星期日
操作系统版本	22000.739
体验	Windows 功能体验包 1000.22000.739.0

 - .Net Version 6.06

**Comment by Simnico99** [comment]
This is actually a limitation of Windows 11 Before build 22523. I can't really do anything about it as I am using their DLL to generate the effect. I could probably try implementing the Acrylic effect from FluentWPF by Sourcechord only for those version but the tabbed won't be available. I will see if I can do something about it in the version 22H2 of windows it should be available.

**Comment by CodingOctocat** [comment]
So the target computer needs Win11 22H2 version to enable acrylic?

**Comment by Simnico99** [comment]
The way this works is it looks for the windows version:
IF Version is higher than 22523 it enables all the options if version is lower it reverts to mica automatically. Because it doesn't work on the lower versions.

**Comment by CodingOctocat** [comment]
Thank you for your reply

**Comment by CodingOctocat** [comment]
> The way this works is it looks for the windows version: IF Version is higher than 22523 it enables all the options if version is lower it reverts to mica automatically. Because it doesn't work on the lower versions.
> 
> So basically Windows Version => 22523 (Release preview,Beta,Dev) Mica,Acrylic,Tabbed
> 
> Windows Version < 22523 Mica

This link explains a lot: [Apply Mica to a WPF app on Windows 11](https://tvc-16.science/mica-wpf.html)

**Comment by Simnico99** [comment]
As it is a Windows Limitation and Windows 11 22H2 is just arround the corner I will consider this issue fixed. Yes people will have to run the new version. 

> > The way this works is it looks for the windows version: IF Version is higher than 22523 it enables all the options if version is lower it reverts to mica automatically. Because it doesn't work on the lower versions.
> > So basically Windows Version => 22523 (Release preview,Beta,Dev) Mica,Acrylic,Tabbed
> > Windows Version < 22523 Mica
> 
> This link explains a lot: [Apply Mica to a WPF app on Windows 11](https://tvc-16.science/mica-wpf.html)

I already use the method used on this website MicaWPF is just a "Wrapper/Interface" that makes it easier to implement and I add brushes and other nice things on top as mentionned on the page you sent:

![image](https://user-images.githubusercontent.com/80013536/177890136-4e64b8ad-2aa0-4286-aae6-726efb9a03c8.png)

Tabbed and Acrylic only works on version 22523+

**Comment by Simnico99** [comment]
Windows 11 22H2 has finally released and now it should work across all versions: Dev,Beta,Release Preview, Release.

**Comment by Simnico99** [comment]
Added to https://github.com/Simnico99/MicaWPF/wiki/Windows-Limitations
Can unpin.
