### ISSUE TITLE
Bug / Error: MicaWPFRuntimeComponent.UWPColors not registered

### ISSUE THREAD

**Issue by Montago** [Simnico99/MicaWPF#25]
System.TypeLoadException: 'Windows-kørselstypen 'MicaWPFRuntimeComponent.UWPColors', der anmodes om, er ikke registreret.'

Roughly translated to Windows cant load MicaWPFRuntimeComponent.UWPColors because its not registered... 

I installed MicaWPF using NUGET into my existing solution and removed all references to the old theme (MahApps Metro) 
I then fixed all bugs .. 

But now the application wont start.

The App is .NET Framework 4.7.2 WPF .. pretty basic. 

I've tried adding the Nuget package MicaWPFRuntimeComponent but that didn't fix anything.

**Comment by Simnico99** [comment]
It is referencing that library for the windows 11 native colors what os are you running and do you use xaml islands?

**Comment by Montago** [comment]
Im running Windows 11, all patched up.

No i don't use XAML Islands , what's that ?

**Comment by Simnico99** [comment]
XAML island are WPF hybrid with UWP. 
I think I nailed the issue down pushing Version 4.2.0 can you try again with this version? (Should be available in the next hour)

**Comment by Montago** [comment]
Thanks I'll try

**Comment by Montago** [comment]
heh i'm now getting a weird error :

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for .NETFramework,**Version=v4.8.1** were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	MicaWPF	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1220
```	
Framework 4.8.1 😄 ?

**Comment by Simnico99** [comment]
If you are using the source itself you need .Net Framework 4.8.1 to compile it:
https://go.microsoft.com/fwlink/?linkid=2203306

**Comment by Montago** [comment]
I removed the NET481 from the target frameworks in the MicaWPF project. 

Now it works !

**Comment by Simnico99** [comment]
.Net 4.8.1 is brand new I think it came out the 9th of august.
