### ISSUE TITLE
AccentColorService.Current will throw exception when using publish the app

### ISSUE THREAD

**Issue by emako** [Simnico99/MicaWPF#30]
When use `build` and run the app is ok, Mica theme is allright.
 But `publish` and run it will throw an exception.
IDE: VS2022 
TargetFramework: net6.0-windows10.0.19041.0
System: Windows11-22H2

```c#
_ = MicaWPF.Services.AccentColorService.Current;
```

and then throw following: (view from system event log)
```js
Application: MyApp.exe
CoreCLR Version: 6.0.1022.47605
.NET Version: 6.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'MicaWPF.Services.AccentColorService' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at WinRT.DllModule.TryCreate(String fileName, DllModule& module)
   at WinRT.DllModule.TryLoad(String fileName, DllModule& module)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at MicaWPFRuntimeComponent.UWPColors..ctor()
   at MicaWPF.Services.AccentColorService.UpdateAccentsFromWindows()
   at MicaWPF.Services.AccentColorService..cctor()
   --- End of inner exception stack trace ---
   at MicaWPF.Services.AccentColorService.get_Current()
   at MyApp.App..ctor() in D:\MyApp\App.xaml.cs:line 14
   at MyApp.App.Main()

```

**Comment by Simnico99** [comment]
I will take a look whenever I am back home today.

**Comment by emako** [comment]
Can provide sample code and binary files if needed.

**Comment by Simnico99** [comment]
Look at your publish settings and be sure to include the Windows build version:
![image](https://user-images.githubusercontent.com/80013536/198374817-34bb12a6-c7d8-4a16-8439-5fbb17fff1ab.png)

**Comment by emako** [comment]
Here is my `FolderProfile.pubxml`, TargetFramework is same as your.
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121.
-->
<Project>
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>x64</Platform>
    <PublishDir>bin\x64\Release\net6.0-windows10.0.19041.0\publish\win-x64\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <_TargetId>Folder</_TargetId>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>
</Project>
```

**Comment by Simnico99** [comment]
Send a sample if possible I will take a deeper look

**Comment by emako** [comment]
[MyMica.zip](https://github.com/Simnico99/MicaWPF/files/9891173/MyMica.zip)
Sample code with bin files here.

Unrunnabled: `publish`
MyMica\bin\Release\net6.0-windows10.0.19041.0\publish\win-x64\MyMica.exe
MyMica\bin\Release\net6.0-windows10.0.19041.0\win-x64\MyMica.exe

Runnabled: `build`
MyMica\bin\Release\net6.0-windows10.0.19041.0\MyMica.exe

**Comment by Simnico99** [comment]
When published via the portable mode it works it only breaks when specifing those:

Doesn't works:
![image](https://user-images.githubusercontent.com/80013536/198750323-7bee31af-3fb8-4c3d-9598-22d8d24aaee1.png)

Works:
![image](https://user-images.githubusercontent.com/80013536/198750342-4c16cd2a-12ab-4cbc-a3af-82dd2c8bb401.png)

Seems to be MicaWPFRuntimeComponents that makes the Windows colors accurate I could add an option to turn it off but Windows colors won't be accurate.

**Comment by emako** [comment]
"Produce single file" seems not the reason.
What the actual reason is Windows colors accurate wrong when `win-x64`?

**Comment by Simnico99** [comment]
For some reasons there seems to be an issue with CsWinRT when using win-x64.
MicaWPFRuntimeComponent needs it in order for it to fetch the actual brushes Windows uses because I can't find their exact algorythms if I fallback to my own the colors are a little bit off. Since Net 5.0 Microsoft removed the support for WindowsApp.SDK.Contracts that is why I need to use a WinRT C++ compononent.

https://github.com/microsoft/CsWinRT
https://github.com/Simnico99/MicaWPFRuntimeComponent

I might try to update the version of CsWinRT.

**Comment by Simnico99** [comment]
Hello,
I've temporarily created a fallback in cases CsWinRT won't load:
https://github.com/Simnico99/MicaWPF/releases/tag/4.8.0
I've tested now it publishes in win-x64

**Comment by emako** [comment]
Tested with [4.8.0](https://github.com/Simnico99/MicaWPF/releases/tag/4.8.0) and it seems fixed.
