### ISSUE TITLE
TitleControlButton ZIndex and position fix

### ISSUE THREAD

**Issue by emako** [Simnico99/MicaWPF#31]
![image](https://user-images.githubusercontent.com/24737061/199500682-2a93513f-3ff6-4aa1-88a2-3725d56dfe50.png)

1. Those TitleControlButton will be covered by other contents, hope some APIs to adujst the ZIndex.

2. Also found that TitleControlButton panel and the window border has a little blank between, it seems not like a native window.

**Comment by Simnico99** [comment]
Added to documentation:
https://github.com/Simnico99/MicaWPF/wiki/MicaWindow--Properties#titlebartype

**Comment by emako** [comment]
That's great. Try it now.
