### ISSUE TITLE
Micawindow background breaks on Windows 10 when another window is opened

### ISSUE THREAD

**Issue by SpringsTS** [Simnico99/MicaWPF#4]
Hello,

A problem I have when I test my application with several WPF windows as MicaWindow on Windows 10:
The first (start-up) one show well, with correct theme and Light/Dark mode.
However, when I create and show another window, <s>I don't have the background working</s>. According if I tweak or not the WindowChrome.GlassFrameThickness, I get either a full-white or full-black background, no matter which Windows Mode I'm using.

Thank you for your answer.

UPDATE: Opening another window break the background on _all_ windows.

**Comment by Simnico99** [comment]
Hello,
Thank you for posting this Issue, Do you have a code snippet I can use to create the other window so it can help me isolate the issue?

P.S I will create a Windows 10 VM and try.

**Comment by Pietro228** [comment]
Hello, I fixed this issue already. I forgot that I created this issue. I was using Modern WPF and it didn't change their color so I had to use ModernWPF window to fix it. But I'm not sure if it is a MicaWPF issue.

**Comment by Pietro228** [comment]
My friend had the same problem on Windows 10.

**Comment by Simnico99** [comment]
I Would like if any of you could try now if it breaks I did a couple of changes 
Be sure to use (1.3.9)

**Comment by Simnico99** [comment]
This issue seems to have been fixed in version 2.0.0
