### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by McNinjaTNT** [Simnico99/MicaWPF#40]
After following the steps in the quick guide on any app I try, it will not launch. It'll give a loading symbol on the cursor but that's it.

I've tried multiple template WPF projects adding mica xmlns etc., and I've tried copy-pasting the code from the quick guide changing only the local namespace and class reference to the proper project namespace.

I've tried .NET 6.0, .NET Framework 4.7.2, and .NET Framework 4.8.1.
Tested running it on a W10 21H1 machine, as well as inside a W11 21H2 VM.

Changing it back to a normal Window always makes it work normally again.

I get exit code -532462766 if that helps.

![App2](https://user-images.githubusercontent.com/69410086/206657368-3e0c3631-85ef-4de5-bc87-7b9a41b7369f.PNG)
![AppCs](https://user-images.githubusercontent.com/69410086/206657369-06673cb9-2f34-4738-a4f9-ebd593015dad.PNG)

**Comment by McNinjaTNT** [comment]
Okay, I narrowed down the issue. Seems work fine on MicaWPF versions before 4.6.1. 4.6.1 and beyond all seem to have the issue

**Comment by McNinjaTNT** [comment]
Bingo! Thanks for the help.
Curios for more details if you're willing to elaborate :)

**Comment by Simnico99** [comment]
I will add this to the docs.

**Comment by Simnico99** [comment]
Added to the docs:
https://github.com/Simnico99/MicaWPF/wiki/Quick-start
