### ISSUE TITLE
Mica overrides transparency

### ISSUE THREAD

**Issue by McNinjaTNT** [Simnico99/MicaWPF#42]
MicaWindow appears to override any manual Transparency setting I set. For example, if I write a border around the main window, and set it's backgroundcolor specifically to transparent, Mica will override it.

This also breaks a DropShadowEffect around the window. The shadow works fine but the transparency behind it is turned into Mica.

On a side note, SystemBackdropType doesn't seem to effect anything. Changing it to None, Tabbed, or Acrylic seems to do nothing in my W11 VM.
Something might be messed up on my end but I've tried it on two projects, with no luck.

**Comment by Simnico99** [comment]
First your Win11 VM needs to be 22H2 or higher (22621.0 or higher) to change to Backdrop type see pinned issue: https://github.com/Simnico99/MicaWPF/issues/21
Run the Winver.exe command to see:
![image](https://user-images.githubusercontent.com/80013536/206834978-2807bec8-13f5-4295-921c-bd7e2e3d64ba.png)

And Indeed Mica effect does override the transparency of the Window it won't affect the controls in but you can't adjust the background transparency with Mica effect on it's a Windows 11 Limitation.

**Comment by McNinjaTNT** [comment]
Gotcha, makes sense. Thanks for the pointer to FluentWPF.

Man that's a dumb limitation, so you can't even have normal transparency anymore? That seems kind of like a big deal to me. The entire alpha channel is taken over by Mica, even with partial opacity.
Anyways, thanks for the info!

**Comment by Simnico99** [comment]
Added a documentation page containing all known Windows Limitations:
https://github.com/Simnico99/MicaWPF/wiki/Windows-Limitations
