### ISSUE TITLE
UI elements appear to get affected by the backdrop

### ISSUE THREAD

**Issue by McNinjaTNT** [Simnico99/MicaWPF#44]
Upon using any effect (Mica and Acrylic tested), UI elements get messed up.

Right half is W10 for reference:
![MicaWPFIssueDark](https://user-images.githubusercontent.com/69410086/210125901-0226909f-fa1c-492d-8c18-dd4b0894bd1c.PNG)
![MicaWPFIssue](https://user-images.githubusercontent.com/69410086/210125902-21f927da-e410-4dd4-89d5-ea33b49d3a05.PNG)

Note the dropdown part looks fine:
![MicaWPFIssueDropdown](https://user-images.githubusercontent.com/69410086/210125956-48e4284a-26a6-40c2-a605-9a4de953ef48.PNG)

This may be due to it being in a VMware VM, however it has no issues with effects in explorer windows etc.
Tested on a fresh WPF .NET Framework 4.7.2 project in a 22H2 VM and 21H2 VM with MicaWPF v4.8.10.

MainWindow.xaml:
```
<mica:MicaWindow x:Class="WpfTestingV2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfTestingV2"
        mc:Ignorable="d"
        Title="MainWindow" Height="350" Width="525"
        xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF" >
    <Grid>
        <Button Width="100" Height="70" Content="TestButton" Background="Red" Margin="0,0,0,40"></Button>
        
        <ComboBox MaxWidth="130" Margin="0,80,0,0">
            <ComboBox.Items>
                <TextBlock Text="Test"></TextBlock>
            </ComboBox.Items>
        </ComboBox>
    </Grid>
</mica:MicaWindow>
```
MainWindow.xaml.cs:
```
using MicaWPF.Controls;

namespace WpfTestingV2
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MicaWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
}
```
App.xaml (I did try MicaLight.xaml too):
```
<Application x:Class="WpfTestingV2.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:WpfTestingV2"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <!-- Note you can change this one to MicaLight -->
                <ResourceDictionary Source="pack://application:,,,/MicaWPF;component/Styles/Themes/MicaDark.xaml" />
                <ResourceDictionary Source="pack://application:,,,/MicaWPF;component/Styles/MicaWPF.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

**Comment by Simnico99** [comment]
Normally I have a UI refresh routine for that it should normally fix it upon theme change I will investigate.

**Comment by McNinjaTNT** [comment]
Not sure if I'm understanding correctly, but this happens regardless of any theme change, and is an issue on app startup.

Thanks for looking into it :)

**Comment by Simnico99** [comment]
The controls are semin transparent if you wanna change the theme use the
ThemeService.Current.ChangeTheme(WindowsTheme.Light); ?

https://github.com/Simnico99/MicaWPF/wiki/Change-Theme-or-Accent-color#changethemewindowstheme

**Comment by McNinjaTNT** [comment]
I tried that, and it changes the theme alright, but the issue still persists with the messed up buttons.
![Animation](https://user-images.githubusercontent.com/69410086/210187746-754f44aa-8430-4522-a03f-3ede48147fca.gif)

**Comment by McNinjaTNT** [comment]
[WpfTestingV2.zip](https://github.com/Simnico99/MicaWPF/files/10333006/WpfTestingV2.zip)
Here's the project files incase you're unable to replicate the issue. Please do let me know if you're able to replicate it or not.

**Comment by McNinjaTNT** [comment]
Update: Setting WindowStyle to None and AllowsTransparency to true fixes the issue, however that causes bigger issues. (No rounded corners, etc.)``

**Comment by Simnico99** [comment]
This is the result I get when I run your test no modifications:
![3be2a8a105cca4e292b7c6edffaddf46](https://user-images.githubusercontent.com/80013536/210510588-4fad6d55-8b3d-402c-baaf-ac5490530788.gif)

**Comment by Simnico99** [comment]
Also to update the colors you should use:
`AccentColorService.Current.UpdateAccents(System.Windows.Media.Color.FromRgb(255, 0, 0));`
And for the button use the following style:
`Style="{StaticResource MicaWPF.Styles.AccentedButton}"`

**Comment by McNinjaTNT** [comment]
I see. Well thanks for looking into it! I suppose it's related to VMware then. I'll comment with an update confirming that once I have a bare metal W11 system to test it on.

P.S: You might want to consider testing this yourself in a VMware VM, as it seems to be an issue with MicaWPF and VMware specifically. (cough there are lots of working VMware Workstation Pro keys on github)
