### ISSUE TITLE
Compatibility mode usage in README is not right

### ISSUE THREAD

**Issue by SlackingVeteran** [Simnico99/MicaWPF#5]
MainWindow.xaml is not of type MicaWindow and MicaWPF.Helpers.MicaHelper.EnableMica is expecting MicaWindow, so the compatibility example does not work at. Is there any possibility to get it fixed?

**Comment by Simnico99** [comment]
I changed the type to use Window instead of MicaWindow.
I will push it to production in the next minutes.
I will keep the issue opened until you confirm me that it is fixed.

**Comment by SlackingVeteran** [comment]
Unrelated to this issue but this was first time I got to try compatibility method and mica effect or even Acrylic or Tabbed did not work.

I am on Windows 11 build 22543. I decided to created a WpfTest app to test library in normal way by setting Window as MicaWindow. Tested with both latest 1.3.3 and 1.3.2 but there seem to be no mica effect at all. I even tried adding `SystemBackdropType="Mica"` and it was still same issue. Tried switching Mica to Acrylic or Tabbed and no effect at all.
I have tried other implementation from scratch like calling `DwmSetWindowAttribute` method with `DWMWA_SYSTEMBACKDROP_TYPE = 38` and it seem to work just fine.

MainWindow.xaml:
```
<mica:MicaWindow  x:Class="WpfTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfTest"
        xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Button Content="Button" HorizontalAlignment="Center" Margin="0,161,0,0" VerticalAlignment="Top" Height="56" Width="167"/>
    </Grid>
</mica:MicaWindow>
```

MainWindow.xaml.cs:
```
using MicaWPF.Controls;

namespace WpfTest
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MicaWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }
    }
}
```

Output:
![image](https://user-images.githubusercontent.com/5356702/151831647-837050f8-a200-4bb6-9ff0-d380689d91a4.png)

**Comment by Simnico99** [comment]
Can you zip the test project and send it to me I will check it?

**Comment by SlackingVeteran** [comment]
sure I can zip and send it. give me a sec

**Comment by SlackingVeteran** [comment]
[MicaTest.zip](https://github.com/Simnico99/MicaWPF/files/7972542/MicaTest.zip)

**Comment by Simnico99** [comment]
Looks like it's an issue with netcoreapp3.1 I will take a deeper look it works when I change the project type to net6.0

**Comment by Simnico99** [comment]
BINGO, netcoreapp3.1 returns a version of Windows 7 and earlier I will fix that and push the update it should fix the issue
Line:
`Version version = Environment.OSVersion.Version;`

**Comment by Simnico99** [comment]
I've update to 1.3.4 I will be awaiting your confirmation before marking this issue as resolved. (Might take a couple of minutes before the NuGet package publish)

**Comment by SlackingVeteran** [comment]
I can confirm all the issues mentioned here has been resolved

**Comment by Simnico99** [comment]
Excellent don't hesitate to open another one if you ever see other issues.
