### ISSUE TITLE
[Bug] CanMinimize&WinUI combination causes TitleBar hidden

### ISSUE THREAD

**Issue by emako** [Simnico99/MicaWPF#51]
**Describe the bug**
When I want to disable the max button (`ResizeMode="CanMinimize"`), but found that the
CanMinimize&WinUI combination causes TitleBar hidden.
Tested under v5.1.0.

**To Reproduce**
```xaml
<mica:MicaWindow x:Class="MyMica.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF"
        xmlns:local="clr-namespace:MyMica"
        ResizeMode="CanMinimize"
        TitleBarType="WinUI"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
    </Grid>
</mica:MicaWindow>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24737061/222831485-ae25537a-a998-4961-aa47-08ccdba4a2e2.png)

**Comment by Simnico99** [comment]
Will work on it once at my PC on ky way back home

**Comment by Simnico99** [comment]
The issue should be fixed in version 5.1.1 can you confirm?

Thank you!

**Comment by Simnico99** [comment]
This issue will be considered as fixed if you still have issues with it don't hesitate to reopen the issue.

Thank you!

**Comment by emako** [comment]
https://github.com/Simnico99/MicaWPF/discussions/57
CanMinimize -> Border resizable: unavailable
