### ISSUE TITLE
Small Typos: ControlsDictionnary and ThemeDictionnary

### ISSUE THREAD

**Issue by jpmikkers** [Simnico99/MicaWPF#55]
**Describe the bug**
Both filenames and classes  for ControlsDictio**nn**ary and ThemeDictio**nn**ary have the same spelling mistake (double n). 

**To Reproduce**
Look at project.

**Expected behavior**
Rename to ControlsDictionary and ThemeDictionary

**Comment by jpmikkers** [comment]
not really a bug obviously.

**Comment by Simnico99** [comment]
> not really a bug obviously.

Indeed but its easy to fix am already working on it.

**Comment by jpmikkers** [comment]
Btw while I'm here, I just love that this is the first WPF lib I found that fixes the border/theming in .net7 on win11 without any problems or code changes.

**Comment by Simnico99** [comment]
Pushing version 5.2.1 typo fixed I also fixed the docs.
