### ISSUE TITLE
[Bug] SnapLayout causes tooltip

### ISSUE THREAD

**Issue by emako** [Simnico99/MicaWPF#59]
![image](https://user-images.githubusercontent.com/24737061/224522889-3c91c295-2a95-4d56-a3d5-7eb420e402ee.png)

It seems that SnapLayout causes tooltip, but other system button not.

**Comment by emako** [comment]
Could all system buttons be displayed consistently or not.

**Comment by Simnico99** [comment]
I think it might be caused by Windows itself and the snap layout api, I will take a look.

**Comment by emako** [comment]
Is will cause when "Show window attachment UI when I hover over a window's maximize button" not checked in System Settings.

**Comment by Simnico99** [comment]
Can you show me what setting exactly? (In english if possible :P)

**Comment by emako** [comment]
Search `snap` in Settings and select the first one.
![image](https://user-images.githubusercontent.com/24737061/226091383-c3543ce4-691b-48ba-ab12-a92a52a34d46.png)


And then uncheck the second item.
![4CIFH)J}~DO@U L F7T}W 3](https://user-images.githubusercontent.com/24737061/226091419-d70d15ba-7a38-4bdc-969d-786a1043031b.png)

**Comment by Simnico99** [comment]
Found the setting I will take a look thank you for the more detailed explaination it helped alot :)

**Comment by Simnico99** [comment]
Pushing 5.2.5 added a check to disable the Snap Layout api completely is it is off in the registry.
It shouldn't do that anymore.

**Comment by emako** [comment]
> Some ideas

Is it high performance to read the registry multiple times from the `WM_NCHITTEST` message?

Would it be better to use `RegistryKey.ValueChanged` instead?
