### ISSUE TITLE
Close button sucks

### ISSUE THREAD

**Issue by StarNumber12046** [Simnico99/MicaWPF#60]
**Describe the bug**
The close button for an app is weird

**To Reproduce**
1. Create a WPF app
2. Apply Mica

**Expected behavior**
It should use the os close (i.e. Windows 11)

**Screenshots**
![image](https://user-images.githubusercontent.com/64470722/225366591-74440c49-42e2-4a96-92ae-d0497981a198.png)
**Desktop (please complete the following information):**
 - OS Version:  Windows 11 [10.0.22621.1265]
 - .Net Version: .NET v7

**Additional context**

**Comment by Simnico99** [comment]
That is the default Win32 Button
Add this
TitleBarType="WinUI"
    
To your window

**Comment by StarNumber12046** [comment]
oh, ok

**Comment by Simnico99** [comment]
Merged, Thanks for the help!
