### ISSUE TITLE
[Feature Request] WinUI close button foreground

### ISSUE THREAD

**Issue by emako** [Simnico99/MicaWPF#66]
**Is your feature request related to a problem? Please describe.**
See following Describe.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/24737061/226145181-8a34ac22-d299-433d-9b8b-9427f63a02ac.png)
Native window in WinUI3 project.
Close button's foreground will be white-like color when mouse hoving.

**Describe alternatives you've considered**

**Additional context**

**Comment by emako** [comment]
It seems that #35 is reproduced in 5.2.6.

**Comment by emako** [comment]
![image](https://user-images.githubusercontent.com/24737061/226839998-33b032f8-4dc1-40ca-8133-87145a614eb3.png)
Leave stuck until mouse moving over MicaWindow.

**Comment by Simnico99** [comment]
Fixed the issue permanently this time releasing version 5.2.7
