### ISSUE TITLE
Title and Icon in Window

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#7]
Setting the `Title` and `Icon` properties of the `MicaWindow` have no effect, and no title and icon are shown.
Can we get these properties to work with `MicaWindow`?

**Comment by Simnico99** [comment]
I will work on adding it in the next release.

**Comment by Simnico99** [comment]
Will be pushed in the new version:
![image](https://user-images.githubusercontent.com/80013536/166445381-94af1cd6-eda4-4885-823f-34ab8a0f4799.png)

**Comment by nlogozzo** [comment]
Beautiful, love it.

**Comment by nlogozzo** [comment]
What about when you double-click on the title bar to maximize the window? Do the title, icon, and caption buttons look cut off? When I click the maximize button it is normal, however, double-clicking the title bar to maximize results in the top bar looking cut off.

**Comment by Simnico99** [comment]
I've added a margin on Maximised window
![image](https://user-images.githubusercontent.com/80013536/166458789-41fc6243-2206-45cf-9e65-5fb1ec2953b1.png)

**Comment by nlogozzo** [comment]
Oh great thanks!

**Comment by nlogozzo** [comment]
May I ask what control library you are using to get that Win 11 Style?

**Comment by Simnico99** [comment]
It's MicaWPF.Extension I will release it with the version 3.0.0 it will add:
TextBox
PasswordBox
RichTextBox
Button (With a accent style)
ProgressBar

I do have the intension to add the other controls too.

**Comment by nlogozzo** [comment]
Beautiful! Love all the work you are doing...reviving WPF for the better since Windows App SDK is a mess. Keep it up 👍

**Comment by Simnico99** [comment]
Thanks! For the update it should be live now if you wanna try 3.0.1 from nuget it should be available in the next minutes.
Tell me if it works fine.

**Comment by nlogozzo** [comment]
Currently in class. Will test the update ASAP and let you know.

**Comment by Simnico99** [comment]
I've pushed 3.0.6 since I was trying on one of my project at it was crashing on start it should be fixed now

**Comment by Simnico99** [comment]
Take not that you now might need to change the CSPROJ target framework if you are using Net5.0+
Here is an exemple:
```Xaml
<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
```
