### ISSUE TITLE
[Feature Request]: More thinned down `ScrollBar`

### ISSUE THREAD

**Issue by shannonfonseka** [Simnico99/MicaWPF#72]
### Describe the solution you'd like

I'd like to suggest an improvement to a feature, that is to thin down the ScrollBar in the ScrollViewer.
The ScrollBar when using MicaWPF looks like this:
![image](https://user-images.githubusercontent.com/58655133/235734771-7293111c-bfcf-41a6-8841-e3f0e1c8f971.png)

I want it to look like this:
![image](https://user-images.githubusercontent.com/58655133/235730305-b74eb800-4af3-4c6d-8b34-5811428ad81a.png)
_Screenshot of Windows Settings, Windows Security and Microsoft Store._

**Comment by Simnico99** [comment]
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/81104219-3aa7-4250-a99b-bdddddffb7f4)
Done should be fixed in the new version I've tested when expanded too it's the same size down to the pixel.
