### ISSUE TITLE
[Bug]: SnapLayout detection when setting never changes

### ISSUE THREAD

**Issue by veler** [Simnico99/MicaWPF#73]
### Describe the bug

I noticed that Windows 11's Snap Layout doesn't work with MicaWPF.

### Steps to reproduce the bug

1. Do a clean install of Windows 11.
2. Create an app that uses MicaWindow.
3. Set the mouse cursor on the Maximize button.
4. Snap Layout won't be displayed

### Expected behavior

Snap layout should be displayed.

I found out why it happens though 😁
By default in Windows 11, Snap Layout is enabled. By default, it looks like the registry key does NOT exist. Therefore, a fix could be updating `IsSnapLayoutEnabled` to return `true` when `registryValueObject == null`.

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### .Net Version

.NET 7.x

**Comment by Simnico99** [comment]
Pushing version 5.3.1 I will await 3 days or your confirmation to close the issue thank you! :)

**Comment by veler** [comment]
I gave it a try and it works! :)

**Comment by Simnico99** [comment]
Thank you for your reply ! :)
