### ISSUE TITLE
[Bug]: Maximize window to cover taskbar height when window width is limited

### ISSUE THREAD

**Issue by CodingOctocat** [Simnico99/MicaWPF#76]
### Describe the bug

If the window is maximized when MaxWidth is set, the contents of the window will overflow to the taskbar.

```XAML
<mica:MicaWindow x:Class="MicaWpfTest.MainWindow"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 xmlns:mica="clr-namespace:MicaWPF.Controls;assembly=MicaWPF"
                 Title="MainWindow"
                 Width="800"
                 Height="450"
                 MaxWidth="1000"
                 SizeToContent="WidthAndHeight"
                 TitleBarType="WinUI"
                 mc:Ignorable="d">
    <StackPanel>
        <mica:Arc Height="30" />

        <mica:Button Content="12321" />

        <mica:TextBox />

        <Button Content="123213213" />
    </StackPanel>
</mica:MicaWindow>
```

![image](https://github.com/Simnico99/MicaWPF/assets/7220248/1d8822ac-e255-454c-9196-12d2a7da8901)

### Steps to reproduce the bug

As above.

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### .Net Version

.NET 7.x

**Comment by Simnico99** [comment]
Without MicaWPF
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/13e8f8e5-7fbf-458f-9920-f2b656c96fb3)

With MicaWPF Maximized with limited height:
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/28305345-2080-4d96-9c43-e3fefdf90784)

I will need more precision has I am not sure to understand what is the issue.

**Comment by CodingOctocat** [comment]
I created a new blank project without MicaWPF and have the same problem, so it's a problem with WPF itself!
Can MicaWPF fix this?

1. Set `MaxWidth`，then maximize window.（title bar is not normal, and Bottom at the back of the taskbar）

![image](https://github.com/Simnico99/MicaWPF/assets/7220248/8b66d45a-2e8c-45be-9aaa-80429153e88d)

The expected result should be something like this:

![image](https://github.com/Simnico99/MicaWPF/assets/7220248/a0d1ea68-7d27-4797-9191-af52f59076d2)

**Comment by Simnico99** [comment]
Ah yes let me take a look at it

**Comment by CodingOctocat** [comment]
We know that if the window is set to `MaxWidth`, then when maximized it will be maximized on the left side of the screen, which is a bad experience, and the correct behavior is to maximize with the window in the center, but it seems like a lot of work to do this, and the behavior of the maximize button has to be override (including double-clicking on the title bar to maximize, Win+UpArrow, and anything else that maximizes the window)

**Comment by Simnico99** [comment]
Do you think I should Actually prevent the user from maximizing the window when the maxwitdh value is not the default?

**Comment by CodingOctocat** [comment]
As shown in the picture:

![image](https://github.com/Simnico99/MicaWPF/assets/7220248/2481deb8-5235-4129-a07a-d8a657fec2a9)

**Comment by Simnico99** [comment]
> As shown in the picture:
> 
> When I maximize the window:
> 
> ![image](https://user-images.githubusercontent.com/7220248/254747789-2481deb8-5235-4129-a07a-d8a657fec2a9.png)

Yes Yes I Understood it's just that I will have to hook into all sort of events to figure this one out.

Its a complex task. I will see what I come up with.

**Comment by Simnico99** [comment]
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/b4e61801-a17a-49fa-b282-8ae9cbaf4ea1)

Works with everything pushing to main branch.

**Comment by Simnico99** [comment]
Pushing version 6.1.3 it is now fixed.
