### ISSUE TITLE
[Feature Request]: Standalone nuget package providing TitleBarContent functionality

### ISSUE THREAD

**Issue by CodingOctocat** [Simnico99/MicaWPF#77]
### Describe the solution you'd like

MicaWPF is a great library, but even for an empty project it is 25MB in size, which seems a bit heavy for developing nice looking tool app.

I see that in the new version, MicaWPF already supports TitleBarContent function, which is a useful feature, can it be branched out separately?

I want to be able to simply customize the title bar, including support for Minimize, Maximize, Close buttons with associated event subscriptions (MaximizingEvent, MaximizdEvent...) For example, I may need to do something before clicking Maximize button.

![image](https://github.com/Simnico99/MicaWPF/assets/7220248/cb773ddc-1abe-4bbe-bef3-014aabd86c01)

**Comment by Simnico99** [comment]
Will be fixed in release 6.0.0 
You can now use MicaWPF.Lite
