### ISSUE TITLE
How To Use MicaWPF.Extension?

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#8]
Could we get some docs on how to use MicaWPF.Extension controls, what styles and namespaces we have to include? Maybe an updated MicaWPF.Demo app to feature some controls too.

Thanks :)

**Comment by Simnico99** [comment]
Working on it, I will probably do it today or tomorrow.

**Comment by Simnico99** [comment]
Added the supported controls to the Main Wiki page + Added Getting started with controls page

https://github.com/Simnico99/MicaWPF/wiki
https://github.com/Simnico99/MicaWPF/wiki/Getting-started-with-controls

I will add documentation to the controls this week.
