### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wintrymichi** [Simnico99/MicaWPF#83]
### Describe the bug

App with micaWPF won't start on light theme

### Steps to reproduce the bug

Activate light theme on windows settings

### Expected behavior

The application should start in light theme

### Screenshots

![immagine](https://github.com/Simnico99/MicaWPF/assets/96500069/877ecc30-17c2-48cd-9fa8-9c8d89ad1255)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 11 version 21H2 (22000), Windows 10 version 22H2 (19045, 2022 Update)

### .Net Version

.NET 6.x

**Comment by Simnico99** [comment]
Works on my side can you send a sample that doesn't work?
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/5a13b963-f6ca-44e6-9817-32e00fc4f0be)

**Comment by jimnastic89** [comment]
Hi there, I'm having the same problem with all versions above 6.0.0 . I've [uploaded a project here](https://github.com/jimnastic89/MicaWPF_Test) with minimal code that causes the following exceptions when trying to start:

TypeInitializationException: The type initializer for 'MicaWPF.Core.Services.MicaWPFServiceUtility' threw an exception.

TargetInvocationException: Exception has been thrown by the target of an invocation.

FileNotFoundException: Could not load file or assembly 'MicaWPFMicaWPF, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by DeBroin** [comment]
Just chiming in to post my findings:
I've had the same issue ever since v6.0, and all versions above.
After reading the above, I did some testing.
If you set the windows 11 Theme to Dark Mode, everything works fine.
As soon as you change "Default App Mode" in settings to "Light", I'm getting the same results as the people above.
According to what I could tell, it's really toggling the default app mode to Light, that triggers this issue.

<img width="473" alt="image" src="https://github.com/Simnico99/MicaWPF/assets/7248571/43e9b9c4-fbfa-4a60-a866-0830399ec0b6">

**Comment by Simnico99** [comment]
> Just chiming in to post my findings: I've had the same issue ever since v6.0, and all versions above. After reading the above, I did some testing. If you set the windows 11 Theme to Dark Mode, everything works fine. As soon as you change "Default App Mode" in settings to "Light", I'm getting the same results as the people above. According to what I could tell, it's really toggling the default app mode to Light, that triggers this issue.
> 
> <img alt="image" width="473" src="https://user-images.githubusercontent.com/7248571/279042864-43e9b9c4-fbfa-4a60-a866-0830399ec0b6.png">

I will download and try on the release version of Windows 11 since I am trying from the Dev version and Canary and it works normally it could be linked to that.

**Comment by Simnico99** [comment]
Nailed the issue down pushing version 6.2.0 tell me if it fixed your issue?

See release notes:
https://github.com/Simnico99/MicaWPF/releases/tag/6.2.0

**Comment by jimnastic89** [comment]
Updated 6.1.3 > 6.2.1 and can confirm it has fixed the issue for me!

**Comment by DeBroin** [comment]
I can confirm as well, fix worked for me. Much appreciated!
