### ISSUE TITLE
Compatibility with HandyControls

### ISSUE THREAD

**Issue by nlogozzo** [Simnico99/MicaWPF#9]
I'm currently using [HandyControls](https://github.com/ghost1372/HandyControls) to give my application a modern look. (Planning on switching to MicaWPF.Extension, once you get all the controls in, but I understand this will take some time)

HandyControls, unfortunately, draws a box around a `Label` whereas with a `TextBlock` it does not. See screenshot:
![image](https://user-images.githubusercontent.com/17648453/166504359-beddeaea-8cdd-4107-b4c1-421c5a4ac8ed.png)

Therefore, because your `TitleBar` uses a `Label` I get the weird effect shown above ^. Therefore, would you be able to switch the `Label` to a `TextBox` so HandyControls and this library play nice together?

Thanks :)

**Comment by Simnico99** [comment]
I didn't see that one coming I will probably use a TextBlock

**Comment by Simnico99** [comment]
Published 3.0.9 Will be ready on NuGet Soon
