### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gabee8** [Simnico99/MicaWPF#90]
### Describe the bug

Hello! I use MicaWPF the Visual Studio 2022. 
The mainwindow.xaml properties window change arrange by category to name or Source, crash designer window if selected <mica:MicaWindow.
Error code:
The XAML Designer has exited unexpectedly. (Exit code: e0434352)

And high cpu usage.

### Steps to reproduce the bug

Click the main window in designer.
Change arrange by category to name or Source (properties window)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### .Net Version

.Net Framework 4.7.x

**Comment by Simnico99** [comment]
Cannot debug Visual studio seems to be related to their error handling

**Comment by Simnico99** [comment]
I also noticed that any WPF applications jumps to high CPU usage (On my computer) too,

**Comment by Simnico99** [comment]
Fixed the issue with High CPU usage I was creating a new brush object alot of time per second instead of using a static one which was doing ALOT of garbage collecting per seconds. Now its fixed for that part.

**Comment by Simnico99** [comment]
Issue fixed in version 6.2.4
