### ISSUE TITLE
[Bug]: Win11 23H2 not works

### ISSUE THREAD

**Issue by hupo376787** [Simnico99/MicaWPF#91]
### Describe the bug

Win11 23H2 not works

### Steps to reproduce the bug

Win11 23H2 not works

### Windows version

Insider Build (xxxxx)

### .Net Version

.NET Core 3.x

**Comment by Simnico99** [comment]
I am running net core 3.1 and the most recent version of windows in the 23H2 channel and it works.
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/929afd25-600f-49e6-82a9-b1d63cfe0cb1)

**Comment by hupo376787** [comment]
Wierd, see mine
![image](https://github.com/Simnico99/MicaWPF/assets/14960168/291c1704-b7b3-46b7-b812-14a5624be1e2)

**Comment by Simnico99** [comment]
You are confusing mica with acrylic:
https://learn.microsoft.com/en-us/windows/apps/design/signature-experiences/materials

Mica:
Light:
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/ad9b4859-f70e-4a17-bfac-385164b0563f)
Dark:
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/b44f3676-2fcf-4339-826b-00f1d9f12450)

Acrylic:
Light
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/a0f71734-f96d-4017-bcc4-37c1d9a0f515)
Dark:
![image](https://github.com/Simnico99/MicaWPF/assets/80013536/07d25ab4-bbed-4e78-93bf-f073d737af09)

Add
` SystemBackdropType="Acrylic" `
 to your window property
 See wiki for more informations
 https://github.com/Simnico99/MicaWPF/wiki/MicaWindow--Properties#systembackdroptype

**Comment by hupo376787** [comment]
Ahhh, thanks, bro.
