### ISSUE TITLE
Windows 10 Fallback Color

### ISSUE THREAD

**Issue by sebaJoSt** [Simnico99/MicaWPF#98]
### Describe the solution you'd like

![image](https://github.com/Simnico99/MicaWPF/assets/388152/3e7c3405-8db5-40b6-8e23-41a8b9d908f9)

The mica effect looks great on my app on Windows 11, even when turning off transparency. However on Windows 10 I get a different color. This makes it harder to design a consistent GUI.  Would it be possible to change the default fallback color on Windows 10 to be the same as the default in Windows 11 (middle pictures) or alternatively make it user-configurable (for light and dark theme)?

**Comment by Simnico99** [comment]
Now it should behave like Win11 with transparency off when you are on Windows 10 can you tell me if it works now?
Version 6.2.7 is being pushed now it should be ready in about 20 / 30 minutes.

**Comment by sebaJoSt** [comment]
Creating the demo I noticed that I had accidentially set a Background Property in `<controls:MicaWindow/>`
It seems that it is used in Windows 10 but not in Windows 11.
Removing it solved the issue...the update to 6.2.7 even fixes the white color so everything looks perfect now.

**Comment by Simnico99** [comment]
Perfect! If you have any other issues don't hesitate to open an issue.
